# Generated by Django 4.0.3 on 2022-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incomestatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Revenue', models.IntegerField(null=True)),
                ('Beginning_Inventory', models.IntegerField()),
                ('Purchases', models.IntegerField()),
                ('Freight_in_Expenses', models.IntegerField()),
                ('Ending_Inventory', models.IntegerField()),
                ('Bill_Of_Materials', models.IntegerField()),
                ('Labour_Charges', models.IntegerField()),
                ('Sub_Contract_Expenses', models.IntegerField()),
                ('Cost_Of_Goods_Sold', models.IntegerField()),
                ('Gross_Profit', models.IntegerField()),
                ('Business_Development_Expenses', models.IntegerField()),
                ('Fuel_Expenses', models.IntegerField()),
                ('Conveyance_Expenses', models.IntegerField()),
                ('Telephone_Expenses', models.IntegerField()),
                ('Selling_and_Admin_Expenses', models.IntegerField()),
                ('Electricity_Charges', models.IntegerField()),
                ('Vehicle_Manitainence', models.IntegerField()),
                ('Machine_Maintainence', models.IntegerField()),
                ('Rent', models.IntegerField()),
                ('Consumables', models.IntegerField()),
                ('Bank_Charges', models.IntegerField()),
                ('Other_Operating_Expenses', models.IntegerField()),
                ('EBITDA', models.IntegerField()),
                ('Depreciation', models.IntegerField()),
                ('Amortization_Expense', models.IntegerField()),
                ('Other_Expenses', models.IntegerField()),
                ('Operating_Profit', models.IntegerField()),
                ('Bank_Interest_Expense', models.IntegerField()),
                ('Other_Interest_Expense', models.IntegerField()),
                ('Total_Interest_Expense', models.IntegerField()),
                ('Bank_Interest_Income', models.IntegerField()),
                ('Other_Interest_Income', models.IntegerField()),
                ('Total_Interest_Income', models.IntegerField()),
                ('Net_Income_Before_Taxes', models.IntegerField()),
                ('Income_Tax_Expense', models.IntegerField()),
                ('Net_Income', models.IntegerField()),
            ],
        ),
    ]
