# Generated by Django 4.0.3 on 2022-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radeapp', '0002_balancesheet_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_deails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=200)),
                ('Company_address', models.CharField(max_length=200)),
                ('Company_type', models.CharField(max_length=50)),
                ('Company_email', models.EmailField(max_length=254)),
                ('Company_Contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Balancesheet',
        ),
        migrations.DeleteModel(
            name='Incomestatement',
        ),
        migrations.DeleteModel(
            name='Ratio',
        ),
    ]
