
from django import forms
from .models import company_deails

class CompanyDetailsForm(forms.ModelForm):
  class Meta:
    model = company_deails
    fields = '__all__'
    
class IncomeStatement_2019(forms.Form):
  Revenue = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Beginning_Inventory = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Purchases = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Freight_in_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Ending_Inventory = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bill_Of_Materials = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Labour_Charges = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Sub_Contract_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Cost_Of_Goods_Sold = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Gross_Profit = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Business_Development_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Fuel_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Conveyance_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Telephone_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Selling_and_Admin_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Electricity_Charges = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Vehicle_Manitainence = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Machine_Maintainence = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Rent = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Consumables = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Charges = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Operating_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  EBITDA = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Depreciation = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Amortization_Expense = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Operating_Profit = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Interest_Expense = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Interest_Expense = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Interest_Expense = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Interest_Income = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Interest_Income = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Interest_Income = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Net_Income_Before_Taxes = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Income_Tax_Expense =forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Net_Income = forms.IntegerField(widget=forms.NumberInput(), initial=0)

class IncomeStatement_2020(forms.Form):
  Revenue1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Beginning_Inventory1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Purchases1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Freight_in_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Ending_Inventory1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bill_Of_Materials1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Labour_Charges1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Sub_Contract_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Cost_Of_Goods_Sold1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Gross_Profit1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Business_Development_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Fuel_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Conveyance_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Telephone_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Selling_and_Admin_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Electricity_Charges1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Vehicle_Manitainence1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Machine_Maintainence1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Rent1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Consumables1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Charges1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Operating_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  EBITDA1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Depreciation1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Amortization_Expense1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Operating_Profit1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Interest_Expense1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Interest_Expense1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Interest_Expense1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Interest_Income1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Interest_Income1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Interest_Income1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Net_Income_Before_Taxes1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Income_Tax_Expense1 =forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Net_Income1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)

class IncomeStatement_2021(forms.Form):
  Revenue2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Beginning_Inventory2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Purchases2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Freight_in_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Ending_Inventory2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bill_Of_Materials2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Labour_Charges2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Sub_Contract_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Cost_Of_Goods_Sold2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Gross_Profit2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Business_Development_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Fuel_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Conveyance_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Telephone_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Selling_and_Admin_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Electricity_Charges2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Vehicle_Manitainence2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Machine_Maintainence2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Rent2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Consumables2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Charges2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Operating_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  EBITDA2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Depreciation2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Amortization_Expense2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Operating_Profit2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Interest_Expense2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Interest_Expense2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Interest_Expense2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Bank_Interest_Income2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Interest_Income2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Interest_Income2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Net_Income_Before_Taxes2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Income_Tax_Expense2 =forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Net_Income2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)


class Balancesheet_2019(forms.Form):
  Cash_And_Cash_Equivalents = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Deposit = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Accounts_Receivable = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Inventory = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Prepaid_Expenses = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Current_Assets = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Current_Assets = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Property_Plant_And_Equipment = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Long_Term_Assets = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Research_and_development = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Intangible_Assets = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Good_Will = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Long_Term_Assets = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Assets = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Accounts_Payable = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Revolving_Debt = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Income_Taxes_Payable = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Current_Portion_Of_Long_Term_Debt = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Current_Liabilities = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Current_Liabilities = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Non_Current_Liabilities = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Long_Term_Liabilities = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Long_Term_Liabilities = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Liabilities = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Capital_Account = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_owners_equity = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_owners_equity_and_liabilities = forms.IntegerField(widget=forms.NumberInput(), initial=0)

class Balancesheet_2020(forms.Form):
  Cash_And_Cash_Equivalents1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Deposit1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Accounts_Receivable1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Inventory1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Prepaid_Expenses1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Current_Assets1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Current_Assets1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Property_Plant_And_Equipment1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Long_Term_Assets1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Research_and_development1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Intangible_Assets1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Good_Will1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Long_Term_Assets1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Assets1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Accounts_Payable1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Revolving_Debt1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Income_Taxes_Payable1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Current_Portion_Of_Long_Term_Debt1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Current_Liabilities1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Current_Liabilities1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Non_Current_Liabilities1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Long_Term_Liabilities1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Long_Term_Liabilities1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Liabilities1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Capital_Account1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_owners_equity1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_owners_equity_and_liabilities1 = forms.IntegerField(widget=forms.NumberInput(), initial=0)

class Balancesheet_2021(forms.Form):
  Cash_And_Cash_Equivalents2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Deposit2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Accounts_Receivable2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Inventory2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Prepaid_Expenses2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Current_Assets2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Current_Assets2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Property_Plant_And_Equipment2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Long_Term_Assets2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Research_and_development2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Intangible_Assets2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Good_Will2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Long_Term_Assets2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Assets2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Accounts_Payable2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Revolving_Debt2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Income_Taxes_Payable2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Current_Portion_Of_Long_Term_Debt2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Current_Liabilities2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Current_Liabilities2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Non_Current_Liabilities2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Other_Long_Term_Liabilities2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Long_Term_Liabilities2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_Liabilities2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Capital_Account2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_owners_equity2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)
  Total_owners_equity_and_liabilities2 = forms.IntegerField(widget=forms.NumberInput(), initial=0)


    