from django.db import models

# Create your models here.
class company_deails(models.Model):
    Company_name = models.CharField(max_length=200)
    Company_address = models.CharField(max_length=200)
    Company_type = models.CharField(max_length=50)
    Company_email = models.EmailField()
    Company_Contact = models.CharField(max_length=10) 
# class Incomestatement(models.Model):
#     Revenue = models.IntegerField(null=True)
#     Beginning_Inventory = models.IntegerField()
#     Purchases = models.IntegerField()
#     Freight_in_Expenses = models.IntegerField()
#     Ending_Inventory = models.IntegerField()
#     Bill_Of_Materials = models.IntegerField()
#     Labour_Charges = models.IntegerField()
#     Sub_Contract_Expenses = models.IntegerField()
#     Cost_Of_Goods_Sold = models.IntegerField()
#     Gross_Profit = models.IntegerField()
#     Business_Development_Expenses = models.IntegerField()
#     Fuel_Expenses = models.IntegerField()  
#     Conveyance_Expenses = models.IntegerField()
#     Telephone_Expenses = models.IntegerField()
#     Selling_and_Admin_Expenses = models.IntegerField()
#     Electricity_Charges = models.IntegerField()  
#     Vehicle_Manitainence = models.IntegerField()
#     Machine_Maintainence = models.IntegerField()
#     Rent = models.IntegerField()
#     Consumables = models.IntegerField()
#     Bank_Charges = models.IntegerField()
#     Other_Operating_Expenses = models.IntegerField()
#     EBITDA = models.IntegerField()
#     Depreciation = models.IntegerField()
#     Amortization_Expense = models.IntegerField()
#     Other_Expenses = models.IntegerField()
#     Operating_Profit = models.IntegerField()
#     Bank_Interest_Expense = models.IntegerField()
#     Other_Interest_Expense = models.IntegerField()
#     Total_Interest_Expense = models.IntegerField()
#     Bank_Interest_Income = models.IntegerField()
#     Other_Interest_Income = models.IntegerField()
#     Total_Interest_Income = models.IntegerField()
#     Net_Income_Before_Taxes = models.IntegerField()
#     Income_Tax_Expense = models.IntegerField()
#     Net_Income = models.IntegerField()
# class Balancesheet(models.Model):
#     Cash_And_Cash_Equivalents = models.IntegerField(null=True)
#     Deposit = models.IntegerField()
#     Accounts_Receivable = models.IntegerField()
#     Inventory = models.IntegerField()
#     Prepaid_Expenses = models.IntegerField()
#     Other_Current_Assets = models.IntegerField()
#     Total_Current_Assets = models.IntegerField()
#     Property_Plant_And_Equipment = models.IntegerField()
#     Other_Long_Term_Assets = models.IntegerField()
#     Research_and_development = models.IntegerField()
#     Intangible_Assets = models.IntegerField()
#     Good_Will = models.IntegerField()
#     Total_Long_Term_Assets = models.IntegerField()
#     Total_Assets = models.IntegerField()
#     Accounts_Payable = models.IntegerField()
#     Revolving_Debt = models.IntegerField()
#     Income_Taxes_Payable = models.IntegerField()
#     Current_Portion_Of_Long_Term_Debt = models.IntegerField()
#     Other_Current_Liabilities = models.IntegerField()
#     Total_Current_Liabilities = models.IntegerField()
#     Non_Current_Liabilities = models.IntegerField()
#     Other_Long_Term_Liabilities = models.IntegerField()
#     Total_Long_Term_Liabilities = models.IntegerField()
#     Total_Liabilities = models.IntegerField()
#     Capital_Account = models.IntegerField()
#     Total_owners_equity = models.IntegerField()
#     Total_owners_equity_and_liabilities = models.IntegerField()
# class Ratio(models.Model):		
#     Current_Ratio = models.IntegerField()		
#     Quick_Ratio = models.IntegerField()				
#     Profitability_Ratios = models.IntegerField()			
#     Return_On_Assets = models.IntegerField()		
#     Return_On_Equity = models.IntegerField()		
#     Gross_Margin = models.IntegerField()	
#     Profit_Margin = models.IntegerField()		
#     Operating_Margin = models.IntegerField()		
#     Activity_Turn_over_Ratios = models.IntegerField()		
#     Asset_Turn_Over = models.IntegerField()		
#     Accounts_Receivable_Turnover = models.IntegerField()		
#     Average_Days_Sales = models.IntegerField()		
#     Days_Receivable = models.IntegerField()		
#     Days_Payable = models.IntegerField()		
#     Inventory_Turnover = models.IntegerField()		
#     Inventory_Turnover_Period = models.IntegerField() 	
#     Working_Capital_Turnover = models.IntegerField()		
#     Ratio_Name = models.IntegerField()		
#     Debt_Ratio = models.IntegerField()		
#     Debt_To_Equity_Ratio = models.IntegerField()				
#     Beginning_Inventory = models.IntegerField()		
#     Purchases = models.IntegerField()	
#     Freight_Expenses = models.IntegerField()		
#     Ending_Inventory = models.IntegerField()		
#     Bill_Of_Materials = models.IntegerField()	
#     Labour_Expenses = models.IntegerField()	
#     Labour_Charges_Per_Working_Hour = models.IntegerField()		
#     Sub_Contract_Expenses = models.IntegerField()		
#     Cost_Of_Goods_Sold = models.IntegerField()		
#     Business_Development_Expenses = models.IntegerField()		
#     Fuel_Expenses = models.IntegerField() 		
#     Conveyance_Expenses = models.IntegerField()		
#     Telephone_Expenses = models.IntegerField()		
#     Selling_Admin_Expenses = models.IntegerField()		
#     Electricity_Charges = models.IntegerField()	
#     Vehicle_Maintenance = models.IntegerField()	
#     Machine_Maintenance = models.IntegerField()		
#     Rent = models.IntegerField()		
#     Consumables = models.IntegerField()		
#     Bank_Charges = models.IntegerField()		
#     Other_Operating_Expenses = models.IntegerField()		
#     EBITDA = models.IntegerField()		
#     Depreciation = models.IntegerField()		
#     Amortization = models.IntegerField()		
#     Other_Expenses = models.IntegerField()		
#     Bank_Interest_Expense = models.IntegerField()   		
#     Other_Interest_Expense = models.IntegerField()		
#     Total_Interest_Expense = models.IntegerField()		
#     Interest_Expense_Per_Working_Hour = models.IntegerField()	
#     Bank_Interest_Income = models.IntegerField()		
#     Other_Interest_Income = models.IntegerField()		
#     Total_Interest_Income = models.IntegerField()  	
#     Net_Income_Before_Taxes = models.IntegerField()		
#     Income_Tax_Expense = models.IntegerField()		




